name: client_deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - dev_FE
jobs: # Job 설정
  build:
    name: Build, Deploy to S3 Bucket
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./client
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v3

      - name: .env setting # .env에 있던 환경변수들을 등록해주는 단계
        run: |
          echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> .env
          echo "REACT_APP_URL=${{ secrets.REACT_APP_URL }}" >> .env
          echo "REACT_APP_TOSS_CLIENT_KEY=${{ secrets.REACT_APP_TOSS_CLIENT_KEY }}" >> .env

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install dependencies # 의존 파일 설치
        run: npm install

      - name: fix babel # babel 오류 해결
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

      - name: Generate build # React Build
        run: npm run build

      - name: Deploy # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_S3 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID_S3 }}
        run: |
          aws s3 sync \
          --region ap-northeast-1 \
          build s3://wonyoungprojects \
          --delete
