name: client_deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - dev_FE
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v3

      - name: Change directory to client # 디렉토리 변경
        run: cd client

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install dependencies # 의존 파일 설치
        run: npm install

      - name: Generate build # React Build
        run: npm run build

      - name: Deploy # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_s3 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_s3 }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://${wonyoungprojects}
